# http://module-build.sourceforge.net/META-spec.html
name:         SVN-S4
version:      1.020
version_from: lib/SVN/S4.pm
license:      perl
installdirs:  site
requires:
    SVN::Client:                    0.000
    IO::AIO:                        0.000
    Digest::MD5:                    0.000
    MIME::Base64:                   0.000
distribution_type: module
generated_by: hand
