# http://module-build.sourceforge.net/META-spec.html
name:         SVN-S4
version:      1.030
version_from: lib/SVN/S4.pm
license:      perl
installdirs:  site
requires:
    SVN::Client:                    0
    IO::AIO:                        0
    Digest::MD5:                    0
    MIME::Base64:                   0

distribution_type: module
generated_by: hand
